import React, { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          display: "flex",
          justifyContent: "space-around",
          alignItems: "center",
          width: "100%",
          height: "100vh",
        }}
      >
        <Link href="/postlist/ssg">
          <a>
            <h1>SSG POSTS</h1>
          </a>
        </Link>
        <Link href="/postlist/ssr">
          <a>
            <h1>SSR POSTS</h1>
          </a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
