import React, { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { IMAGE_URL } from "../config/util";

const Home: NextPage = () => {
  useEffect(() => {
    const apiKey = process.env.NEXT_PUBLIC_CLIENT_ID;
    fetch(`${IMAGE_URL}/random?client_id=${apiKey}`)
      .then((res) => console.log(res))
      .catch((err) => console.log(err));
  });
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          display: "flex",
          justifyContent: "space-around",
          alignItems: "center",
          width: "100%",
          height: "100vh",
        }}
      >
        <Link href="/postlist/ssg">
          <a>
            <h1>SSG POSTS</h1>
          </a>
        </Link>
        <Link href="/postlist/ssr">
          <a>
            <h1>SSR POSTS</h1>
          </a>
        </Link>
        <Link href="/postlist/csr">
          <a>
            <h1>CSR POSTS</h1>
          </a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
